import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet' />
      </Head>
      <body className="bg-white dark:bg-slate-900 dark:text-white body-font ">
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}