name: build

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16.5']
        language: [ 'en']

    name: build next
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - run: |
          ls > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          ls
          yarn install
      - name: Build site
        run: |
          yarn build
