name: build

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16.5']
        language: [ 'en']

    name: build next
    steps:
      - uses: actions/setup-node@v3.3.0
        with:
          fetch-depth: 0
          
      - name: Set up Node ${{ matrix.node-version }}
        - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        shell: bash
        run: |
          yarn install

      - name: Build site
        shell: bash
        run: |
          yarn build
